#!/bin/bash
wget https://files.rcsb.org/download/6VI0.cif
wget https://files.rcsb.org/download/7UCF.cif
wget https://files.rcsb.org/download/5CEZ.cif
wget https://files.rcsb.org/download/6DE7.cif
wget https://files.rcsb.org/download/6B0N.cif
wget https://files.rcsb.org/download/6PDU.cif
wget https://files.rcsb.org/download/6PDR.cif
wget https://files.rcsb.org/download/6VPX.cif
wget https://files.rcsb.org/download/6PDS.cif
wget https://files.rcsb.org/download/6OT1.cif
wget https://files.rcsb.org/download/7N65.cif
wget https://files.rcsb.org/download/5U1F.cif
wget https://files.rcsb.org/download/6OSY.cif
wget https://files.rcsb.org/download/6N16.cif
wget https://files.rcsb.org/download/6PEF.cif
wget https://files.rcsb.org/download/6PEC.cif
wget https://files.rcsb.org/download/6NIJ.cif
wget https://files.rcsb.org/download/5I8H.cif
wget https://files.rcsb.org/download/6OZC.cif
wget https://files.rcsb.org/download/4ZMJ.cif
wget https://files.rcsb.org/download/5JSA.cif
wget https://files.rcsb.org/download/6MN7.cif
wget https://files.rcsb.org/download/6V6W.cif
wget https://files.rcsb.org/download/6CRQ.cif
wget https://files.rcsb.org/download/6E5P.cif
wget https://files.rcsb.org/download/7L8T.cif
wget https://files.rcsb.org/download/6WIX.cif
wget https://files.rcsb.org/download/7T0O.cif
wget https://files.rcsb.org/download/6CK9.cif
wget https://files.rcsb.org/download/6VY2.cif
wget https://files.rcsb.org/download/6UM5.cif
wget https://files.rcsb.org/download/6W03.cif
wget https://files.rcsb.org/download/6XRT.cif
wget https://files.rcsb.org/download/6UDJ.cif
wget https://files.rcsb.org/download/6VO1.cif
wget https://files.rcsb.org/download/6VO0.cif
wget https://files.rcsb.org/download/5VJ6.cif
wget https://files.rcsb.org/download/7LXN.cif
wget https://files.rcsb.org/download/6UM6.cif
wget https://files.rcsb.org/download/6UM7.cif
wget https://files.rcsb.org/download/7LXM.cif
wget https://files.rcsb.org/download/5U7M.cif
wget https://files.rcsb.org/download/6OZ4.cif
wget https://files.rcsb.org/download/7LPN.cif
wget https://files.rcsb.org/download/5VIY.cif
wget https://files.rcsb.org/download/5I8C.cif
wget https://files.rcsb.org/download/6IEQ.cif
wget https://files.rcsb.org/download/5JS9.cif
wget https://files.rcsb.org/download/5U7O.cif
wget https://files.rcsb.org/download/7TFN.cif
wget https://files.rcsb.org/download/5T3Z.cif
wget https://files.rcsb.org/download/7LG6.cif
wget https://files.rcsb.org/download/6CHB.cif
wget https://files.rcsb.org/download/5T3X.cif
wget https://files.rcsb.org/download/5FYL.cif
wget https://files.rcsb.org/download/6NF2.cif
wget https://files.rcsb.org/download/7TFO.cif
wget https://files.rcsb.org/download/6UCF.cif
wget https://files.rcsb.org/download/6VN0.cif
wget https://files.rcsb.org/download/5FYK.cif
wget https://files.rcsb.org/download/6X97.cif
wget https://files.rcsb.org/download/6UCE.cif
wget https://files.rcsb.org/download/6X98.cif
wget https://files.rcsb.org/download/7LX2.cif
wget https://files.rcsb.org/download/6MTJ.cif
wget https://files.rcsb.org/download/6OPA.cif
wget https://files.rcsb.org/download/7KMD.cif
wget https://files.rcsb.org/download/6UTK.cif
wget https://files.rcsb.org/download/5V8M.cif
wget https://files.rcsb.org/download/6NNJ.cif
wget https://files.rcsb.org/download/7RSN.cif
wget https://files.rcsb.org/download/5V8L.cif
wget https://files.rcsb.org/download/7LOK.cif
wget https://files.rcsb.org/download/7LX3.cif
wget https://files.rcsb.org/download/6NNF.cif
wget https://files.rcsb.org/download/6MTN.cif
wget https://files.rcsb.org/download/6X9U.cif
wget https://files.rcsb.org/download/6X9V.cif
wget https://files.rcsb.org/download/6X9S.cif
wget https://files.rcsb.org/download/6UDA.cif
wget https://files.rcsb.org/download/6X9T.cif
wget https://files.rcsb.org/download/6MU8.cif
wget https://files.rcsb.org/download/6X9R.cif
wget https://files.rcsb.org/download/6MU6.cif
wget https://files.rcsb.org/download/6MU7.cif
wget https://files.rcsb.org/download/6P8D.cif
wget https://files.rcsb.org/download/6UBI.cif
wget https://files.rcsb.org/download/6VLR.cif
wget https://files.rcsb.org/download/7MXE.cif
wget https://files.rcsb.org/download/7RAI.cif
wget https://files.rcsb.org/download/6NM6.cif
wget https://files.rcsb.org/download/6WWC.cif
wget https://files.rcsb.org/download/6DID.cif
wget https://files.rcsb.org/download/7KDE.cif
wget https://files.rcsb.org/download/5V7J.cif
wget https://files.rcsb.org/download/7LO6.cif
wget https://files.rcsb.org/download/6X96.cif
wget https://files.rcsb.org/download/5CJX.cif
wget https://files.rcsb.org/download/6CH7.cif
wget https://files.rcsb.org/download/6CH8.cif
wget https://files.rcsb.org/download/6WX2.cif
wget https://files.rcsb.org/download/6MZJ.cif
wget https://files.rcsb.org/download/6NCP.cif
wget https://files.rcsb.org/download/5UTY.cif
wget https://files.rcsb.org/download/6VKN.cif
wget https://files.rcsb.org/download/6P7H.cif
wget https://files.rcsb.org/download/6MAR.cif
wget https://files.rcsb.org/download/5TKJ.cif
wget https://files.rcsb.org/download/5TKK.cif
wget https://files.rcsb.org/download/4TVP.cif
wget https://files.rcsb.org/download/5D9Q.cif
wget https://files.rcsb.org/download/6NC2.cif
wget https://files.rcsb.org/download/5C7K.cif
wget https://files.rcsb.org/download/6P6F.cif
wget https://files.rcsb.org/download/6MQE.cif
wget https://files.rcsb.org/download/6NC3.cif
wget https://files.rcsb.org/download/6MQC.cif
wget https://files.rcsb.org/download/6MYY.cif
wget https://files.rcsb.org/download/7LLK.cif
wget https://files.rcsb.org/download/5UTF.cif
wget https://files.rcsb.org/download/6U0N.cif
wget https://files.rcsb.org/download/7LU9.cif
wget https://files.rcsb.org/download/6U0L.cif
wget https://files.rcsb.org/download/6MQR.cif
wget https://files.rcsb.org/download/6MQS.cif
wget https://files.rcsb.org/download/7MDT.cif
wget https://files.rcsb.org/download/6V0R.cif
wget https://files.rcsb.org/download/6CDE.cif
wget https://files.rcsb.org/download/6MPG.cif
wget https://files.rcsb.org/download/6MPH.cif
wget https://files.rcsb.org/download/7PC2.cif
wget https://files.rcsb.org/download/5THR.cif
wget https://files.rcsb.org/download/6CDM.cif
wget https://files.rcsb.org/download/6P60.cif
wget https://files.rcsb.org/download/7N6U.cif
wget https://files.rcsb.org/download/6CDI.cif
wget https://files.rcsb.org/download/6CM3.cif
wget https://files.rcsb.org/download/5W6D.cif
wget https://files.rcsb.org/download/5FUU.cif
wget https://files.rcsb.org/download/6CUF.cif
wget https://files.rcsb.org/download/6N1W.cif
wget https://files.rcsb.org/download/6N1V.cif
wget https://files.rcsb.org/download/6OLP.cif
wget https://files.rcsb.org/download/6CUE.cif
wget https://files.rcsb.org/download/7N6W.cif
wget https://files.rcsb.org/download/7LL2.cif
wget https://files.rcsb.org/download/6CDO.cif
wget https://files.rcsb.org/download/6CE0.cif
wget https://files.rcsb.org/download/5ACO.cif
wget https://files.rcsb.org/download/6PW6.cif
wget https://files.rcsb.org/download/7LL1.cif
wget https://files.rcsb.org/download/6CDP.cif

